[workspace]
members = [".", "typed-arrow-derive"]

[package]
name = "typed-arrow"
version = "0.1.0"
edition = "2021"
description = "Compile-time Arrow schemas for Rust."
license = "Apache-2.0"
readme = "README.md"
resolver = "2"

[lib]
name = "typed_arrow"
path = "src/lib.rs"

[features]
default = ["derive"]
derive = ["dep:typed-arrow-derive"]

[dependencies]
typed-arrow-derive = { path = "typed-arrow-derive", optional = true, package = "typed-arrow-derive" }
arrow-array = { version = "56" }
arrow-schema = { version = "56" }
arrow-buffer = { version = "56" }
half = "2"
